"""Capture & Media domain: ``UploadSession`` and ``ObjectKeyPolicy`` (ST-008; ADR 0011).

Pure Python (ddd-guidelines §4.5). The session decides, for every tus PATCH, whether the
chunk is accepted and whether it becomes an S3 multipart part or a staging object. The
adapter does the I/O and then commits the plan. ``offset`` is always the number of bytes
durably stored, so a refused chunk never changes it.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum

from racket.platform.errors import (
    Conflict,
    PayloadTooLarge,
    UploadOffsetMismatch,
    ValidationFailed,
)


class OffsetMismatch(UploadOffsetMismatch):
    pass


class ChunkBeyondLength(PayloadTooLarge):
    pass


class InvalidUploadLength(ValidationFailed):
    pass


class UploadIncomplete(Conflict):
    pass


class UploadAlreadyComplete(Conflict):
    """A finished upload takes no more bytes, not even an empty chunk (SEC-R1-02)."""


class UploadStatus(StrEnum):
    RECEIVING = "receiving"
    COMPLETE = "complete"
    EXPIRED = "expired"


@dataclass(frozen=True)
class Part:
    number: int
    etag: str
    size: int


@dataclass(frozen=True)
class StagedChunk:
    offset: int
    size: int
    key: str


@dataclass(frozen=True)
class ChunkPlan:
    """What to do with one accepted chunk. ``staged`` are earlier chunks to prepend."""

    offset: int
    size: int
    as_part: bool
    part_number: int | None
    staged: tuple[StagedChunk, ...]
    completes: bool

    @property
    def new_offset(self) -> int:
        return self.offset + self.size

    @property
    def is_noop(self) -> bool:
        """An empty chunk: nothing is written and the offset stays (R1-01)."""
        return self.size == 0


class ObjectKeyPolicy:
    """Object keys are generated by the server, never derived from user input [AQS/SEC-02]."""

    def original_key(self) -> str:
        return f"originals/{uuid.uuid4().hex}"

    @staticmethod
    def staging_key(upload_id: uuid.UUID, offset: int) -> str:
        return f"staging/{upload_id.hex}/{offset:020d}"


def _now() -> datetime:
    return datetime.now(UTC)


@dataclass(eq=False)
class UploadSession:
    id: uuid.UUID
    owner_id: uuid.UUID
    match_id: uuid.UUID
    length: int
    object_key: str
    s3_upload_id: str
    offset: int = 0
    parts: list[Part] = field(default_factory=list)
    staged: list[StagedChunk] = field(default_factory=list)
    status: UploadStatus = UploadStatus.RECEIVING
    media_asset_id: uuid.UUID | None = None
    created_at: datetime = field(default_factory=_now)
    updated_at: datetime = field(default_factory=_now)

    @classmethod
    def start(
        cls,
        *,
        owner_id: uuid.UUID,
        match_id: uuid.UUID,
        length: int,
        max_length: int,
        object_key: str,
        s3_upload_id: str,
        upload_id: uuid.UUID | None = None,
    ) -> UploadSession:
        if not 1 <= length <= max_length:
            raise InvalidUploadLength("declared length is out of range")
        return cls(
            id=upload_id or uuid.uuid4(),
            owner_id=owner_id,
            match_id=match_id,
            length=length,
            object_key=object_key,
            s3_upload_id=s3_upload_id,
        )

    @property
    def is_complete(self) -> bool:
        return self.offset == self.length

    @property
    def staged_bytes(self) -> int:
        return sum(s.size for s in self.staged)

    def plan_chunk(self, offset: int, size: int, part_min_bytes: int) -> ChunkPlan:
        """Accept or refuse a chunk. The offset check comes first (ADR 0011 step 1).

        A finished upload refuses every chunk (SEC-R1-02). An empty chunk while receiving is
        a no-op plan: it must not be staged, because its staging key would equal the next
        chunk's key and the part would hold those bytes twice (R1-01)."""
        if offset != self.offset:
            raise OffsetMismatch("chunk does not start at the stored offset")
        if self.status == UploadStatus.COMPLETE or self.is_complete:
            raise UploadAlreadyComplete("upload is complete")
        if size < 0 or offset + size > self.length:
            raise ChunkBeyondLength("chunk goes past the declared length")
        if size == 0:
            return ChunkPlan(offset, 0, as_part=False, part_number=None, staged=(),
                             completes=False)  # fmt: skip
        completes = offset + size == self.length
        as_part = completes or self.staged_bytes + size >= part_min_bytes
        return ChunkPlan(
            offset=offset,
            size=size,
            as_part=as_part,
            part_number=len(self.parts) + 1 if as_part else None,
            staged=tuple(self.staged) if as_part else (),
            completes=completes,
        )

    def commit_part(self, plan: ChunkPlan, *, etag: str) -> None:
        self._check_plan(plan)
        if not plan.as_part or plan.part_number is None:
            raise ValueError("plan is not a part")
        size = plan.size + sum(s.size for s in plan.staged)
        # Reassign (never mutate in place) so the persistence layer sees the change.
        self.parts = [*self.parts, Part(plan.part_number, etag, size)]
        self.staged = []
        self._advance(plan)

    def commit_staged(self, plan: ChunkPlan, *, staging_key: str) -> None:
        self._check_plan(plan)
        if plan.as_part:
            raise ValueError("plan is a part")
        if any(s.offset == plan.offset or s.key == staging_key for s in self.staged):
            raise ValueError("offset or key already staged")
        self.staged = [*self.staged, StagedChunk(plan.offset, plan.size, staging_key)]
        self._advance(plan)

    def mark_complete(self, media_asset_id: uuid.UUID | None = None) -> None:
        if not self.is_complete:
            raise UploadIncomplete("upload has not received its last byte")
        self.status = UploadStatus.COMPLETE
        self.media_asset_id = media_asset_id
        self.updated_at = _now()

    def _check_plan(self, plan: ChunkPlan) -> None:
        if plan.is_noop:
            raise ValueError("an empty chunk is never committed")
        if plan.offset != self.offset:
            raise OffsetMismatch("upload moved on since the chunk was planned")

    def _advance(self, plan: ChunkPlan) -> None:
        self.offset = plan.new_offset
        self.updated_at = _now()
